sf:
  key: "3MVG97quAmFZJfVy2Ox4602qRvLO47cfOR7.xPuBiHTtXh9UuQonr8trdHx.c7ehx3_DU3YyOy95oSeZqVwb_"
  secret: "815574BC0628BD1C7A9F3774AC3156ABBDE4BB6F0CCC7DB1F11B50329BA33E27"
  username: "sivendu@njclabs.com"
  password: "Njclabs@903"
  token: "CWGFpPeAhZgHyu1wiXZkjz65G"